#!/bin/bash -l

# DEBUG IPM CORE SYSTEM

self_dir=$(dirname "$0")/../ipm-core/;
cd $self_dir
cargo fmt

./build-ipm
if [ $? -ne 0 ]; then
  echo "cargo build failed"
  exit 1
fi
ipm=./ipm/bin/ipm
commands=(
  "$ipm version"
  "$ipm help"
  "$ipm update"
  "sudo $ipm install ../ipm-packages/ipm-default"
  "$ipm list"
)

results=()

for cmd in "${commands[@]}"; do
  echo "Running: $cmd"
  if $cmd; then
    results+=("$cmd: SUCCESS")
  else
    results+=("$cmd: FAILURE")
  fi
  sleep 1
done

echo "


" #scroll
echo "Summary of results:"
for result in "${results[@]}"; do
  echo "$result"
done
