name: IPM Debug Build

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check IPM Core
      run: ./ipm-core/debug
    - name: Build and Package IPM Core
      run: ./build/script
